# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: HUR Group
# Description of the Site
description: Welcome to HUR Group at GIST
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: HUR Group, Mechanical Engineering, GIST, Pilwon Hur, Free Energy Principle
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: pilwonhur@gist.ac.kr
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Pilwon Hur
# URL for the Image of the Author
author-image: https://hurgroup.net/sub/external/data/research_scheme.png
# https://hurgroup.net/sub/external/data/pilwonhur.jpg
# 60 Words About the Author
author-about: The HUR group, established in September 2014 with Dr. Pilwon Hur's appointment as an Assistant Professor in the Department of Mechanical Engineering at Texas A&M University, has since evolved significantly. By December 2020, Dr. Hur transitioned to the School of Mechanical Engineering at GIST in South Korea, assuming the role of Associate Professor. The acronym "HUR" encapsulates various meanings, reflecting the group's dynamic focus; 1) HUman Rehabilitation, emphasizing the human-centric approach to rehabilitation; 2) Humans Union Robots, symbolizing the synergy between humans and robots; 3) Humans, You (U), and Robots, highlighting the collaborative relationship; and 4) it represents Dr. Hur's last name, underscoring his foundational role in the group. <br><br> The primary objectives of the HUR group are twofold. First, they aim to unravel the complexities of how the central nervous system orchestrates human sensorimotor behavior in a Bayesian optimal manner. Second, they are dedicated to the development and control of robots designed for autonomous and seamless interaction with humans, serving multiple roles such as assistance and rehabilitation. The accompanying schematic provides a comprehensive overview of the group's research areas and key focal points.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

port: 8080

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
